# Generated by Django 2.2.16 on 2022-04-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220407_1649'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_object_following',
        ),
    ]
